# Generated by Django 2.2.4 on 2020-07-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='alias',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='last_name',
        ),
    ]
