# Generated by Django 2.2.4 on 2020-07-23 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200723_1721'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantedWishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='content.Wishes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_granted_wishes', to='login.Registration')),
            ],
        ),
    ]
