# Generated by Django 2.2.4 on 2020-07-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_grantedwishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='granted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='GrantedWishes',
        ),
    ]
